//************************************************************************************
//**  
//**  Source name:   C:\Users\medel\OneDrive - MATRIX TECHNOLOGY SOLUTIONS\FC10\Components\IO_Source\DSP\DSP_Interlace.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.16F.16F877A
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Thursday, October 30, 2025 15:41:09
//**  Users:         1
//**  Registered to: medelec35 (65920724)
//**  Licence key: 5Q78FW
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#include "C:\Users\medel\OneDrive - MATRIX TECHNOLOGY SOLUTIONS\FC10\Components\IO_Source\DSP\DSP_Interlace.h"

#define FCA_REF16 0x1010
#define FCV_REF16 0x00f9
#define FCA_REF15 0xc10f
#define FCV_REF15 0x00ed
#define FCA_REF14 0xc10e
#define FCV_REF14 0x00e1
#define FCA_REF13 0xc10d
#define FCV_REF13 0x00d5
#define FCA_REF12 0xc10c
#define FCV_REF12 0x00c9
#define FCA_REF11 0xc10b
#define FCV_REF11 0x00bd
#define FCA_REF10 0xc10a
#define FCV_REF10 0x00b1
#define FCA_REF9 0xc109
#define FCV_REF9 0x00a5
#define FCA_REF8 0xc108
#define FCV_REF8 0x0099
#define FCA_REF7 0xc107
#define FCV_REF7 0x008d
#define FCA_REF6 0xc106
#define FCV_REF6 0x0081
#define FCA_REF5 0xc105
#define FCV_REF5 0x0075
#define FCA_REF4 0xc104
#define FCV_REF4 0x0069
#define FCA_REF3 0xc103
#define FCV_REF3 0x005d
#define FCA_REF2 0xc102
#define FCV_REF2 0x0051
#define FCA_REF1 0xc101
#define FCV_REF1 0x0039
#define FCA_GDITEXT2 0x2262
#define FCV_GDITEXT2 0x0037
#define FCA_GDISHAPE2 0x6f62
#define FCV_GDISHAPE2 0x0035
#define FCA_GDICOMPLEXSHAPE1 0x08e2
#define FCV_GDICOMPLEXSHAPE1 0x0033
#define FCA_GDISHAPE1 0x6f61
#define FCV_GDISHAPE1 0x0031
#define FCA_TYPECONVERSIONSFREE1 0x2571
#define FCV_TYPECONVERSIONSFREE1 0x0021

/*========================================================================*\
   Use :TypeConversionsFree1
       :GUID: 3e8d8ce5-379f-45cf-99dc-b2d57e3c1964
       :Location: C:\Users\medel\OneDrive - MATRIX TECHNOLOGY SOLUTIONS\FC10\Components\nonrelease\TypeConversionsFree.fcpx
       :Version: 1.0 (0x100028)*
       :Timestamp: 0
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :Sets a single 16-bit INT value.
       :Index is in little endian, 0 is the LSW and 1 is the MSW
       :
       :Parameters for macro SetInt:
       :  Index : Range: 0-1
       :  Value : Range: 0-65535
\*=----------------------------------------------------------------------=*/
void FCD_02571_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE)
{

  if (FCL_INDEX < 2)
  {  

    // C Code
    MX_Conv_Var.AsInt[FCL_INDEX] = FCL_VALUE;

  // } else {

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 32-bit LONG value
       :
       :Parameters for macro SetLong:
       :  Value : Range: 0-4294967295
\*=----------------------------------------------------------------------=*/
void FCD_02571_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE)
{

  // C Code
  MX_Conv_Var.AsLong = FCL_VALUE;

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 32-bit FLOAT value
       :
       :Returns : MX_FLOAT
\*=----------------------------------------------------------------------=*/
MX_FLOAT FCD_02571_TypeConversionsFree1__GetFloat()
{
  //Local variable definitions
  MX_FLOAT FCR_RETVAL;


  // C Code
  FCR_RETVAL = MX_Conv_Var.AsFloat;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 32-bit LONG value
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCD_02571_TypeConversionsFree1__GetLong()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL;


  // C Code
  FCR_RETVAL = MX_Conv_Var.AsLong;

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 16-bit INT value
       :Index is in little endian, 0 is the LSW and 1 is the MSW
       :
       :Parameters for macro GetInt:
       :  Index : Range: 0-1
       :
       :Returns : MX_UINT16
\*=----------------------------------------------------------------------=*/
MX_UINT16 FCD_02571_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX)
{
  //Local variable definitions
  MX_UINT16 FCR_RETVAL;


  if (FCL_INDEX < 2)
  {  

    // C Code
    FCR_RETVAL = MX_Conv_Var.AsInt[FCL_INDEX];

  } else {

    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 8-bit BYTE value
       :Index is in little endian, 0 is the LSB and 3 is the MSB
       :
       :Parameters for macro SetByte:
       :  Index : Range: 0-3
       :  Value : Range: 0-255
\*=----------------------------------------------------------------------=*/
void FCD_02571_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE)
{

  if (FCL_INDEX < 4)
  {  

    // C Code
    MX_Conv_Var.AsByte[FCL_INDEX] = FCL_VALUE;

  // } else {

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Gets a single 8-bit BYTE value.
       :Index is in little endian, 0 is the LSB and 3 is the MSB
       :
       :Parameters for macro GetByte:
       :  Index : Range: 0-3
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_02571_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX)
{
  //Local variable definitions
  MX_UINT8 FCR_RETVAL;


  if (FCL_INDEX < 4)
  {  

    // C Code
    FCR_RETVAL = MX_Conv_Var.AsByte[FCL_INDEX];

  } else {

    FCR_RETVAL = 0;

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sets a single 32-bit FLOAT value
       :
       :Parameters for macro SetFloat:
       :  Value : Range: 0-4294967295
\*=----------------------------------------------------------------------=*/
void FCD_02571_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE)
{

  // C Code
  MX_Conv_Var.AsFloat = FCL_VALUE;

}

#define FCA_BUFF1 0x9991
#define FCV_BUFF1 0x000d

/*========================================================================*\
   Use :Buff1
       :GUID: 08d7f73a-6b9f-47fa-aa34-b306613d1e51
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\Buff.fcpx
       :Version: 16.0 (0x100028)
       :Timestamp: 06\05\2025
       :Variable declarations
       :Macro implementations
\*========================================================================*/
MX_GLOBAL MX_UINT32 FCV_09991_Buff1__CONSOLEHANDLE;
MX_GLOBAL MX_UINT32 FCV_09991_Buff1__GROUPHANDLE;


/*========================================================================*\
   Use :User Project
       :Variable declarations
       :Macro implementations
\*========================================================================*/
MX_GLOBAL MX_UINT8 FCV_SOURCE = (0x0);
MX_GLOBAL MX_UINT16 FCV_INDEXOUT = (0x0);

/*=----------------------------------------------------------------------=*\
   Use :Called back on the panel command System.TimerStart
       :
       :Parameters for macro Ev_Timer:
       :  TimerID : The identifier passed to the System.TimerStart panel command
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Timer(MX_UINT32 FCL_TIMERID)
{
  //Local variable definitions
  #define FCLsz_TEMP_STR 20
  MX_CHAR FCL_TEMP_STR[FCLsz_TEMP_STR];
  MX_UINT32 FCL_HANDLE;
  MX_UINT8 FCL_IDX;
  MX_UINT32 FCR_RETVAL;


  // Loop
  for (FCL_IDX=0; (FCL_IDX)<(16); (FCL_IDX)++)
  {
    // Calculation
    {
    MX_CHAR FCI_TMP_STR[MX_MAX_TMPSTR_SIZE];
    FCI_SHEAD("Ref",4, FCI_TOSTRING(FCL_IDX + 1, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE),20, FCL_TEMP_STR,20);
    }

    // Built-in Function
    // .Handle=::Component.FindChild(this, .temp_str)

    // Decision
    if (FCL_IDX < 2)
    {    

      // Built-in Function
      // ::System.Forward(.Handle)

    // } else {

    }

  }

  // Built-in Function
  // ::System.Forward(Buff1)

  return (FCR_RETVAL);

  //Local variable definitions
  #undef FCLsz_TEMP_STR
}

/*=----------------------------------------------------------------------=*\
   Use :Sent when a property has been changed by the User
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Property()
{
  //Local variable definitions
  #define FCLsz_TEMP_STR 20
  MX_CHAR FCL_TEMP_STR[FCLsz_TEMP_STR];
  MX_FLOAT FCL_CALC;
  MX_UINT16 FCL_BYTECOUNT = (0x0);
  MX_UINT32 FCL_HANDLE;
  MX_FLOAT FCL_DIV;
  MX_FLOAT FCL_Y;
  MX_UINT8 FCL_IDX;
  MX_UINT32 FCR_RETVAL;


  // Simulation
  // .temp_str=::Tree.GetName(this)

  // Simulation
  // ::Component.Property.SetValue(GdiText2, "sText", .temp_str)

  // Built-in Function
  // .Handle=::Component.GetParent(this)

  // Decision
  if (FCL_HANDLE)
  {  

    // Calculation
    FCL_DIV = 25.0;

  } else {

    // Calculation
    FCL_DIV = 1.0;

  }

  // Simulation
  // ::Panel.Position.ScaleTo(GdiShape1, 20 / .Div, ((NumInputs * 6.0) + 8.0) / .Div, (1.0)/ .Div)

  // Decision
  if (2 & 1)
  {  

    // Calculation
    FCL_Y = (flt_mul((flt_div((2 - 1), 2.0)), 20.0));

  } else {

    // Calculation
    FCL_Y = flt_add((flt_mul((flt_div((2 - 2), 2.0)), 20.0)), 10.0);

  }

  // Loop
  for (FCL_IDX=0; (FCL_IDX)<(16); (FCL_IDX)++)
  {
    // Calculation
    {
    MX_CHAR FCI_TMP_STR[MX_MAX_TMPSTR_SIZE];
    FCI_SHEAD("Ref",4, FCI_TOSTRING(FCL_IDX + 1, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE),20, FCL_TEMP_STR,20);
    }

    // Built-in Function
    // .Handle=::Component.FindChild(this, .temp_str)

    // Decision
    if (FCL_IDX < 2)
    {    

      // Simulation
      // ::Panel.Position.MoveTo(.Handle, -40 / .Div, .Y / .Div, 1.0 / .Div)

      // Calculation
      FCL_Y = flt_sub(FCL_Y, 20.0);

    } else {

      // Simulation
      // ::Panel.Position.MoveTo(.Handle, -40 / .Div, 0.0 / .Div, 1.0 / .Div)

    }

  }

  // Simulation
  // ::Panel.Position.MoveTo(GdiShape2, 0.0, -(((NumInputs - 2) * 9.8) + 25.0) / .Div, -1.0 / .Div)

  // Simulation
  // ::Panel.Position.MoveTo(GdiText2, 0.0, -(((NumInputs - 2) * 9.8) + 40.0) / .Div, 1.0 / .Div)

  // Simulation
  // .temp_str=::Component.Property.GetValue(Ref1, "BuffSize")

  // Simulation
  // ::Component.Property.SetValue(this, "BuffSizeIn", .temp_str)

  // Simulation
  // .temp_str=::Component.Property.GetValue(Ref1, "BuffType")

  // Simulation
  // ::Component.Property.SetValue(this, "BuffTypeIn", .temp_str)

  // Calculation
  FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

  // Decision
  if (2 > 1)
  {  

    // Simulation
    // ::Component.SetVisible(Ref2, 1)

    // Simulation
    // ::Component.Property.SetVisible(Ref2, "LinkTo", 1)

    // Simulation
    // .temp_str=::Component.Property.GetValue(Ref2, "BuffSize")

    // Simulation
    // ::Component.Property.SetValue(this, "BuffSizeIn2", .temp_str)

    // Simulation
    // .temp_str=::Component.Property.GetValue(Ref2, "BuffType")

    // Simulation
    // ::Component.Property.SetValue(this, "BuffTypeIn2", .temp_str)

    // Calculation
    FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

    // Decision
    if (2 > 2)
    {    

      // Simulation
      // ::Component.SetVisible(Ref3, 1)

      // Simulation
      // ::Component.Property.SetVisible(Ref3, "LinkTo", 1)

      // Simulation
      // .temp_str=::Component.Property.GetValue(Ref3, "BuffSize")

      // Simulation
      // ::Component.Property.SetValue(this, "BuffSizeIn3", .temp_str)

      // Simulation
      // .temp_str=::Component.Property.GetValue(Ref3, "BuffType")

      // Simulation
      // ::Component.Property.SetValue(this, "BuffTypeIn3", .temp_str)

      // Calculation
      FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

      // Decision
      if (2 > 3)
      {      

        // Simulation
        // ::Component.SetVisible(Ref4, 1)

        // Simulation
        // ::Component.Property.SetVisible(Ref4, "LinkTo", 1)

        // Simulation
        // .temp_str=::Component.Property.GetValue(Ref4, "BuffSize")

        // Simulation
        // ::Component.Property.SetValue(this, "BuffSizeIn4", .temp_str)

        // Simulation
        // .temp_str=::Component.Property.GetValue(Ref4, "BuffType")

        // Simulation
        // ::Component.Property.SetValue(this, "BuffTypeIn4", .temp_str)

        // Calculation
        FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

        // Decision
        if (2 > 4)
        {        

          // Simulation
          // ::Component.SetVisible(Ref5, 1)

          // Simulation
          // ::Component.Property.SetVisible(Ref5, "LinkTo", 1)

          // Simulation
          // .temp_str=::Component.Property.GetValue(Ref5, "BuffSize")

          // Simulation
          // ::Component.Property.SetValue(this, "BuffSizeIn5", .temp_str)

          // Simulation
          // .temp_str=::Component.Property.GetValue(Ref5, "BuffType")

          // Simulation
          // ::Component.Property.SetValue(this, "BuffTypeIn5", .temp_str)

          // Calculation
          FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

          // Decision
          if (2 > 5)
          {          

            // Simulation
            // ::Component.SetVisible(Ref6, 1)

            // Simulation
            // ::Component.Property.SetVisible(Ref6, "LinkTo", 1)

            // Simulation
            // .temp_str=::Component.Property.GetValue(Ref6, "BuffSize")

            // Simulation
            // ::Component.Property.SetValue(this, "BuffSizeIn6", .temp_str)

            // Simulation
            // .temp_str=::Component.Property.GetValue(Ref6, "BuffType")

            // Simulation
            // ::Component.Property.SetValue(this, "BuffTypeIn6", .temp_str)

            // Calculation
            FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

            // Decision
            if (2 > 6)
            {            

              // Simulation
              // ::Component.SetVisible(Ref7, 1)

              // Simulation
              // ::Component.Property.SetVisible(Ref7, "LinkTo", 1)

              // Simulation
              // .temp_str=::Component.Property.GetValue(Ref7, "BuffSize")

              // Simulation
              // ::Component.Property.SetValue(this, "BuffSizeIn7", .temp_str)

              // Simulation
              // .temp_str=::Component.Property.GetValue(Ref7, "BuffType")

              // Simulation
              // ::Component.Property.SetValue(this, "BuffTypeIn7", .temp_str)

              // Calculation
              FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

              // Decision
              if (2 > 7)
              {              

                // Simulation
                // ::Component.SetVisible(Ref8, 1)

                // Simulation
                // ::Component.Property.SetVisible(Ref8, "LinkTo", 1)

                // Simulation
                // .temp_str=::Component.Property.GetValue(Ref8, "BuffSize")

                // Simulation
                // ::Component.Property.SetValue(this, "BuffSizeIn8", .temp_str)

                // Simulation
                // .temp_str=::Component.Property.GetValue(Ref8, "BuffType")

                // Simulation
                // ::Component.Property.SetValue(this, "BuffTypeIn8", .temp_str)

                // Calculation
                FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                // Decision
                if (2 > 8)
                {                

                  // Simulation
                  // ::Component.SetVisible(Ref9, 1)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref9, "LinkTo", 1)

                  // Simulation
                  // .temp_str=::Component.Property.GetValue(Ref9, "BuffSize")

                  // Simulation
                  // ::Component.Property.SetValue(this, "BuffSizeIn9", .temp_str)

                  // Simulation
                  // .temp_str=::Component.Property.GetValue(Ref9, "BuffType")

                  // Simulation
                  // ::Component.Property.SetValue(this, "BuffTypeIn9", .temp_str)

                  // Calculation
                  FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                  // Decision
                  if (2 > 9)
                  {                  

                    // Simulation
                    // ::Component.SetVisible(Ref10, 1)

                    // Simulation
                    // ::Component.Property.SetVisible(Ref10, "LinkTo", 1)

                    // Simulation
                    // .temp_str=::Component.Property.GetValue(Ref10, "BuffSize")

                    // Simulation
                    // ::Component.Property.SetValue(this, "BuffSizeIn10", .temp_str)

                    // Simulation
                    // .temp_str=::Component.Property.GetValue(Ref10, "BuffType")

                    // Simulation
                    // ::Component.Property.SetValue(this, "BuffTypeIn10", .temp_str)

                    // Calculation
                    FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                    // Decision
                    if (2 > 10)
                    {                    

                      // Simulation
                      // ::Component.SetVisible(Ref11, 1)

                      // Simulation
                      // ::Component.Property.SetVisible(Ref11, "LinkTo", 1)

                      // Simulation
                      // .temp_str=::Component.Property.GetValue(Ref11, "BuffSize")

                      // Simulation
                      // ::Component.Property.SetValue(this, "BuffSizeIn11", .temp_str)

                      // Simulation
                      // .temp_str=::Component.Property.GetValue(Ref11, "BuffType")

                      // Simulation
                      // ::Component.Property.SetValue(this, "BuffTypeIn11", .temp_str)

                      // Calculation
                      FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                      // Decision
                      if (2 > 11)
                      {                      

                        // Simulation
                        // ::Component.SetVisible(Ref12, 1)

                        // Simulation
                        // ::Component.Property.SetVisible(Ref12, "LinkTo", 1)

                        // Simulation
                        // .temp_str=::Component.Property.GetValue(Ref12, "BuffSize")

                        // Simulation
                        // ::Component.Property.SetValue(this, "BuffSizeIn12", .temp_str)

                        // Simulation
                        // .temp_str=::Component.Property.GetValue(Ref12, "BuffType")

                        // Simulation
                        // ::Component.Property.SetValue(this, "BuffTypeIn12", .temp_str)

                        // Calculation
                        FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                        // Decision
                        if (2 > 12)
                        {                        

                          // Simulation
                          // ::Component.SetVisible(Ref13, 1)

                          // Simulation
                          // ::Component.Property.SetVisible(Ref13, "LinkTo", 1)

                          // Simulation
                          // .temp_str=::Component.Property.GetValue(Ref13, "BuffSize")

                          // Simulation
                          // ::Component.Property.SetValue(this, "BuffSizeIn13", .temp_str)

                          // Simulation
                          // .temp_str=::Component.Property.GetValue(Ref13, "BuffType")

                          // Simulation
                          // ::Component.Property.SetValue(this, "BuffTypeIn13", .temp_str)

                          // Calculation
                          FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                          // Decision
                          if (2 > 13)
                          {                          

                            // Simulation
                            // ::Component.SetVisible(Ref14, 1)

                            // Simulation
                            // ::Component.Property.SetVisible(Ref14, "LinkTo", 1)

                            // Simulation
                            // .temp_str=::Component.Property.GetValue(Ref14, "BuffSize")

                            // Simulation
                            // ::Component.Property.SetValue(this, "BuffSizeIn14", .temp_str)

                            // Simulation
                            // .temp_str=::Component.Property.GetValue(Ref14, "BuffType")

                            // Simulation
                            // ::Component.Property.SetValue(this, "BuffTypeIn14", .temp_str)

                            // Calculation
                            FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                            // Decision
                            if (2 > 14)
                            {                            

                              // Simulation
                              // ::Component.SetVisible(Ref15, 1)

                              // Simulation
                              // ::Component.Property.SetVisible(Ref15, "LinkTo", 1)

                              // Simulation
                              // .temp_str=::Component.Property.GetValue(Ref15, "BuffSize")

                              // Simulation
                              // ::Component.Property.SetValue(this, "BuffSizeIn15", .temp_str)

                              // Simulation
                              // .temp_str=::Component.Property.GetValue(Ref15, "BuffType")

                              // Simulation
                              // ::Component.Property.SetValue(this, "BuffTypeIn15", .temp_str)

                              // Calculation
                              FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                              // Decision
                              if (2 > 15)
                              {                              

                                // Simulation
                                // ::Component.SetVisible(Ref16, 1)

                                // Simulation
                                // ::Component.Property.SetVisible(Ref16, "LinkTo", 1)

                                // Simulation
                                // .temp_str=::Component.Property.GetValue(Ref16, "BuffSize")

                                // Simulation
                                // ::Component.Property.SetValue(this, "BuffSizeIn16", .temp_str)

                                // Simulation
                                // .temp_str=::Component.Property.GetValue(Ref16, "BuffType")

                                // Simulation
                                // ::Component.Property.SetValue(this, "BuffTypeIn16", .temp_str)

                                // Calculation
                                FCL_BYTECOUNT = FCL_BYTECOUNT + FCM_Prv_GetTypeBytes(FCL_TEMP_STR, FCLsz_TEMP_STR);

                              } else {

                                // Simulation
                                // ::Component.SetVisible(Ref16, 0)

                                // Simulation
                                // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                                // Call Component Macro
                                // Ref16::SetHandle(0)

                              }

                            } else {

                              // Simulation
                              // ::Component.SetVisible(Ref15, 0)

                              // Simulation
                              // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

                              // Call Component Macro
                              // Ref15::SetHandle(0)

                              // Simulation
                              // ::Component.SetVisible(Ref16, 0)

                              // Simulation
                              // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                              // Call Component Macro
                              // Ref16::SetHandle(0)

                            }

                          } else {

                            // Simulation
                            // ::Component.SetVisible(Ref14, 0)

                            // Simulation
                            // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

                            // Call Component Macro
                            // Ref14::SetHandle(0)

                            // Simulation
                            // ::Component.SetVisible(Ref15, 0)

                            // Simulation
                            // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

                            // Call Component Macro
                            // Ref15::SetHandle(0)

                            // Simulation
                            // ::Component.SetVisible(Ref16, 0)

                            // Simulation
                            // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                            // Call Component Macro
                            // Ref16::SetHandle(0)

                          }

                        } else {

                          // Simulation
                          // ::Component.SetVisible(Ref13, 0)

                          // Simulation
                          // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

                          // Call Component Macro
                          // Ref13::SetHandle(0)

                          // Simulation
                          // ::Component.SetVisible(Ref14, 0)

                          // Simulation
                          // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

                          // Call Component Macro
                          // Ref14::SetHandle(0)

                          // Simulation
                          // ::Component.SetVisible(Ref15, 0)

                          // Simulation
                          // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

                          // Call Component Macro
                          // Ref15::SetHandle(0)

                          // Simulation
                          // ::Component.SetVisible(Ref16, 0)

                          // Simulation
                          // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                          // Call Component Macro
                          // Ref16::SetHandle(0)

                        }

                      } else {

                        // Simulation
                        // ::Component.SetVisible(Ref12, 0)

                        // Simulation
                        // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

                        // Call Component Macro
                        // Ref12::SetHandle(0)

                        // Simulation
                        // ::Component.SetVisible(Ref13, 0)

                        // Simulation
                        // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

                        // Call Component Macro
                        // Ref13::SetHandle(0)

                        // Simulation
                        // ::Component.SetVisible(Ref14, 0)

                        // Simulation
                        // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

                        // Call Component Macro
                        // Ref14::SetHandle(0)

                        // Simulation
                        // ::Component.SetVisible(Ref15, 0)

                        // Simulation
                        // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

                        // Call Component Macro
                        // Ref15::SetHandle(0)

                        // Simulation
                        // ::Component.SetVisible(Ref16, 0)

                        // Simulation
                        // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                        // Call Component Macro
                        // Ref16::SetHandle(0)

                      }

                    } else {

                      // Simulation
                      // ::Component.SetVisible(Ref11, 0)

                      // Simulation
                      // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

                      // Call Component Macro
                      // Ref11::SetHandle(0)

                      // Simulation
                      // ::Component.SetVisible(Ref12, 0)

                      // Simulation
                      // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

                      // Call Component Macro
                      // Ref12::SetHandle(0)

                      // Simulation
                      // ::Component.SetVisible(Ref13, 0)

                      // Simulation
                      // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

                      // Call Component Macro
                      // Ref13::SetHandle(0)

                      // Simulation
                      // ::Component.SetVisible(Ref14, 0)

                      // Simulation
                      // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

                      // Call Component Macro
                      // Ref14::SetHandle(0)

                      // Simulation
                      // ::Component.SetVisible(Ref15, 0)

                      // Simulation
                      // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

                      // Call Component Macro
                      // Ref15::SetHandle(0)

                      // Simulation
                      // ::Component.SetVisible(Ref16, 0)

                      // Simulation
                      // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                      // Call Component Macro
                      // Ref16::SetHandle(0)

                    }

                  } else {

                    // Simulation
                    // ::Component.SetVisible(Ref10, 0)

                    // Simulation
                    // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

                    // Call Component Macro
                    // Ref10::SetHandle(0)

                    // Simulation
                    // ::Component.SetVisible(Ref11, 0)

                    // Simulation
                    // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

                    // Call Component Macro
                    // Ref11::SetHandle(0)

                    // Simulation
                    // ::Component.SetVisible(Ref12, 0)

                    // Simulation
                    // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

                    // Call Component Macro
                    // Ref12::SetHandle(0)

                    // Simulation
                    // ::Component.SetVisible(Ref13, 0)

                    // Simulation
                    // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

                    // Call Component Macro
                    // Ref13::SetHandle(0)

                    // Simulation
                    // ::Component.SetVisible(Ref14, 0)

                    // Simulation
                    // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

                    // Call Component Macro
                    // Ref14::SetHandle(0)

                    // Simulation
                    // ::Component.SetVisible(Ref15, 0)

                    // Simulation
                    // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

                    // Call Component Macro
                    // Ref15::SetHandle(0)

                    // Simulation
                    // ::Component.SetVisible(Ref16, 0)

                    // Simulation
                    // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                    // Call Component Macro
                    // Ref16::SetHandle(0)

                  }

                } else {

                  // Simulation
                  // ::Component.SetVisible(Ref9, 0)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref9, "LinkTo", 0)

                  // Call Component Macro
                  // Ref9::SetHandle(0)

                  // Simulation
                  // ::Component.SetVisible(Ref10, 0)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

                  // Call Component Macro
                  // Ref10::SetHandle(0)

                  // Simulation
                  // ::Component.SetVisible(Ref11, 0)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

                  // Call Component Macro
                  // Ref11::SetHandle(0)

                  // Simulation
                  // ::Component.SetVisible(Ref12, 0)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

                  // Call Component Macro
                  // Ref12::SetHandle(0)

                  // Simulation
                  // ::Component.SetVisible(Ref13, 0)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

                  // Call Component Macro
                  // Ref13::SetHandle(0)

                  // Simulation
                  // ::Component.SetVisible(Ref14, 0)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

                  // Call Component Macro
                  // Ref14::SetHandle(0)

                  // Simulation
                  // ::Component.SetVisible(Ref15, 0)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

                  // Call Component Macro
                  // Ref15::SetHandle(0)

                  // Simulation
                  // ::Component.SetVisible(Ref16, 0)

                  // Simulation
                  // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                  // Call Component Macro
                  // Ref16::SetHandle(0)

                }

              } else {

                // Simulation
                // ::Component.SetVisible(Ref8, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref8, "LinkTo", 0)

                // Call Component Macro
                // Ref8::SetHandle(0)

                // Simulation
                // ::Component.SetVisible(Ref9, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref9, "LinkTo", 0)

                // Call Component Macro
                // Ref9::SetHandle(0)

                // Simulation
                // ::Component.SetVisible(Ref10, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

                // Call Component Macro
                // Ref10::SetHandle(0)

                // Simulation
                // ::Component.SetVisible(Ref11, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

                // Call Component Macro
                // Ref11::SetHandle(0)

                // Simulation
                // ::Component.SetVisible(Ref12, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

                // Call Component Macro
                // Ref12::SetHandle(0)

                // Simulation
                // ::Component.SetVisible(Ref13, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

                // Call Component Macro
                // Ref13::SetHandle(0)

                // Simulation
                // ::Component.SetVisible(Ref14, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

                // Call Component Macro
                // Ref14::SetHandle(0)

                // Simulation
                // ::Component.SetVisible(Ref15, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

                // Call Component Macro
                // Ref15::SetHandle(0)

                // Simulation
                // ::Component.SetVisible(Ref16, 0)

                // Simulation
                // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

                // Call Component Macro
                // Ref16::SetHandle(0)

              }

            } else {

              // Simulation
              // ::Component.SetVisible(Ref7, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref7, "LinkTo", 0)

              // Call Component Macro
              // Ref7::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref8, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref8, "LinkTo", 0)

              // Call Component Macro
              // Ref8::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref9, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref9, "LinkTo", 0)

              // Call Component Macro
              // Ref9::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref10, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

              // Call Component Macro
              // Ref10::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref11, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

              // Call Component Macro
              // Ref11::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref12, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

              // Call Component Macro
              // Ref12::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref13, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

              // Call Component Macro
              // Ref13::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref14, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

              // Call Component Macro
              // Ref14::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref15, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

              // Call Component Macro
              // Ref15::SetHandle(0)

              // Simulation
              // ::Component.SetVisible(Ref16, 0)

              // Simulation
              // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

              // Call Component Macro
              // Ref16::SetHandle(0)

            }

          } else {

            // Simulation
            // ::Component.SetVisible(Ref6, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref6, "LinkTo", 0)

            // Call Component Macro
            // Ref6::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref7, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref7, "LinkTo", 0)

            // Call Component Macro
            // Ref7::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref8, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref8, "LinkTo", 0)

            // Call Component Macro
            // Ref8::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref9, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref9, "LinkTo", 0)

            // Call Component Macro
            // Ref9::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref10, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

            // Call Component Macro
            // Ref10::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref11, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

            // Call Component Macro
            // Ref11::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref12, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

            // Call Component Macro
            // Ref12::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref13, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

            // Call Component Macro
            // Ref13::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref14, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

            // Call Component Macro
            // Ref14::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref15, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

            // Call Component Macro
            // Ref15::SetHandle(0)

            // Simulation
            // ::Component.SetVisible(Ref16, 0)

            // Simulation
            // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

            // Call Component Macro
            // Ref16::SetHandle(0)

          }

        } else {

          // Simulation
          // ::Component.SetVisible(Ref5, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref5, "LinkTo", 0)

          // Call Component Macro
          // Ref5::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref6, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref6, "LinkTo", 0)

          // Call Component Macro
          // Ref6::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref7, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref7, "LinkTo", 0)

          // Call Component Macro
          // Ref7::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref8, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref8, "LinkTo", 0)

          // Call Component Macro
          // Ref8::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref9, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref9, "LinkTo", 0)

          // Call Component Macro
          // Ref9::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref10, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

          // Call Component Macro
          // Ref10::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref11, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

          // Call Component Macro
          // Ref11::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref12, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

          // Call Component Macro
          // Ref12::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref13, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

          // Call Component Macro
          // Ref13::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref14, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

          // Call Component Macro
          // Ref14::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref15, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

          // Call Component Macro
          // Ref15::SetHandle(0)

          // Simulation
          // ::Component.SetVisible(Ref16, 0)

          // Simulation
          // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

          // Call Component Macro
          // Ref16::SetHandle(0)

        }

      } else {

        // Simulation
        // ::Component.SetVisible(Ref4, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref4, "LinkTo", 0)

        // Call Component Macro
        // Ref4::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref5, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref5, "LinkTo", 0)

        // Call Component Macro
        // Ref5::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref6, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref6, "LinkTo", 0)

        // Call Component Macro
        // Ref6::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref7, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref7, "LinkTo", 0)

        // Call Component Macro
        // Ref7::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref8, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref8, "LinkTo", 0)

        // Call Component Macro
        // Ref8::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref9, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref9, "LinkTo", 0)

        // Call Component Macro
        // Ref9::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref10, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

        // Call Component Macro
        // Ref10::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref11, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

        // Call Component Macro
        // Ref11::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref12, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

        // Call Component Macro
        // Ref12::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref13, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

        // Call Component Macro
        // Ref13::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref14, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

        // Call Component Macro
        // Ref14::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref15, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

        // Call Component Macro
        // Ref15::SetHandle(0)

        // Simulation
        // ::Component.SetVisible(Ref16, 0)

        // Simulation
        // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

        // Call Component Macro
        // Ref16::SetHandle(0)

      }

    } else {

      // Simulation
      // ::Component.SetVisible(Ref3, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref3, "LinkTo", 0)

      // Call Component Macro
      // Ref3::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref4, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref4, "LinkTo", 0)

      // Call Component Macro
      // Ref4::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref5, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref5, "LinkTo", 0)

      // Call Component Macro
      // Ref5::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref6, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref6, "LinkTo", 0)

      // Call Component Macro
      // Ref6::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref7, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref7, "LinkTo", 0)

      // Call Component Macro
      // Ref7::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref8, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref8, "LinkTo", 0)

      // Call Component Macro
      // Ref8::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref9, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref9, "LinkTo", 0)

      // Call Component Macro
      // Ref9::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref10, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

      // Call Component Macro
      // Ref10::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref11, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

      // Call Component Macro
      // Ref11::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref12, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

      // Call Component Macro
      // Ref12::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref13, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

      // Call Component Macro
      // Ref13::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref14, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

      // Call Component Macro
      // Ref14::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref15, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

      // Call Component Macro
      // Ref15::SetHandle(0)

      // Simulation
      // ::Component.SetVisible(Ref16, 0)

      // Simulation
      // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

      // Call Component Macro
      // Ref16::SetHandle(0)

    }

  } else {

    // Simulation
    // ::Component.SetVisible(Ref2, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref2, "LinkTo", 0)

    // Call Component Macro
    // Ref2::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref3, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref3, "LinkTo", 0)

    // Call Component Macro
    // Ref3::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref4, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref4, "LinkTo", 0)

    // Call Component Macro
    // Ref4::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref5, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref5, "LinkTo", 0)

    // Call Component Macro
    // Ref5::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref6, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref6, "LinkTo", 0)

    // Call Component Macro
    // Ref6::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref7, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref7, "LinkTo", 0)

    // Call Component Macro
    // Ref7::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref8, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref8, "LinkTo", 0)

    // Call Component Macro
    // Ref8::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref9, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref9, "LinkTo", 0)

    // Call Component Macro
    // Ref9::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref10, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref10, "LinkTo", 0)

    // Call Component Macro
    // Ref10::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref11, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref11, "LinkTo", 0)

    // Call Component Macro
    // Ref11::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref12, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref12, "LinkTo", 0)

    // Call Component Macro
    // Ref12::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref13, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref13, "LinkTo", 0)

    // Call Component Macro
    // Ref13::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref14, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref14, "LinkTo", 0)

    // Call Component Macro
    // Ref14::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref15, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref15, "LinkTo", 0)

    // Call Component Macro
    // Ref15::SetHandle(0)

    // Simulation
    // ::Component.SetVisible(Ref16, 0)

    // Simulation
    // ::Component.Property.SetVisible(Ref16, "LinkTo", 0)

    // Call Component Macro
    // Ref16::SetHandle(0)

  }

  // Decision
  if (1 < 1)
  {  

    // Simulation
    // ::Component.Property.SetValue(this, "DataCount", 1)

  // } else {

  }

  // Simulation
  // ::Component.Property.SetValue(this, "BuffSize", .ByteCount)

  // Simulation
  // ::Component.Property.CopyValue(this, Buff1, "BuffSize")

  // Simulation
  // ::Component.Property.CopyValue(this, Buff1, "BuffType")

  return (FCR_RETVAL);

  //Local variable definitions
  #undef FCLsz_TEMP_STR
}

/*=----------------------------------------------------------------------=*\
   Use :Broadcast after a project has finished loading
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_LoadComplete()
{
  //Local variable definitions
  MX_UINT32 FCR_RETVAL;


  // Built-in Function
  // ::System.TimerStart(0, 6000)

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Parameters for macro Prv_GetTypeBytes:
       :  typestr[20] : MX_CHAR (by-ref)
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCM_Prv_GetTypeBytes(MX_CHAR *FCL_TYPESTR, MX_UINT16 FCLsz_TYPESTR)
{
  //Local variable definitions
  MX_UINT8 FCL_TYPE;
  MX_UINT8 FCR_RETVAL;


  // Calculation
  FCL_TYPE = FCI_STRING_TO_INT(FCL_TYPESTR, FCLsz_TYPESTR);

  // Decision
  if (FCL_TYPE == 0)
  {  

    // Calculation
    FCR_RETVAL = 1;

  } else {

    // Decision
    if (FCL_TYPE < 3)
    {    

      // Calculation
      FCR_RETVAL = 2;

    } else {

      // Calculation
      FCR_RETVAL = 4;

    }

  }

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Sent to a component to allow dynamic amendment of global constant declarations
       :
       :Parameters for macro Ev_AddVar:
       :  VarName[20] : The original Flowcode variable
       :  ExpandName[20] : The expanded variable name
       :  Expansion[20] : The expanded string to inline to the code
       :
       :Returns : Non-zero to include definition - initialised on call
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_AddVar(MX_CHAR *PFCL_VARNAME, MX_CHAR *PFCL_EXPANDNAME, MX_CHAR *FCL_EXPANSION, MX_UINT16 FCLsz_EXPANSION)
{
  //Local variable definitions
  MX_UINT8 FCL_IDX;
  #define FCLsz_VARSTR 20
  MX_CHAR FCL_VARSTR[FCLsz_VARSTR];
  #define FCLsz_PROPSTR 20
  MX_CHAR FCL_PROPSTR[FCLsz_PROPSTR];
  MX_UINT16 FCL_SIZE;
  MX_UINT32 FCR_RETVAL; // Non-zero to include definition - initialised on call

  #define FCLsz_VARNAME 20
  MX_CHAR FCL_VARNAME[FCLsz_VARNAME];
  FCI_CONCATENATE(PFCL_VARNAME,FCLsz_VARNAME,"",0,FCL_VARNAME,FCLsz_VARNAME);
  #define FCLsz_EXPANDNAME 20
  MX_CHAR FCL_EXPANDNAME[FCLsz_EXPANDNAME];
  FCI_CONCATENATE(PFCL_EXPANDNAME,FCLsz_EXPANDNAME,"",0,FCL_EXPANDNAME,FCLsz_EXPANDNAME);


  // Calculation
  FCR_RETVAL = 1;

  // Loop
  for (FCL_IDX=0; (FCL_IDX)<(16); (FCL_IDX)++)
  {
    // Calculation
    {
    MX_CHAR FCI_TMP_STR[MX_MAX_TMPSTR_SIZE];
    FCI_SHEAD("IndexIn",8, FCI_UTOS8(FCL_IDX, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE),20, FCL_VARSTR,20);
    }

    // Decision
    if (FCL_IDX == 0)
    {    

      // Calculation
      FCI_SCOPY("BuffSizeIn",11, FCL_PROPSTR,FCLsz_PROPSTR);

    } else {

      // Calculation
      {
      MX_CHAR FCI_TMP_STR[MX_MAX_TMPSTR_SIZE];
      FCI_SHEAD("BuffSizeIn",11, FCI_UTOS8(FCL_IDX, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE),20, FCL_PROPSTR,20);
      }

    }

    // Decision
    if (FCI_COMPARE(FCL_VARNAME, FCLsz_VARNAME, FCL_VARSTR, FCLsz_VARSTR, 0) == 0)
    {    

      // Decision
      if (FCL_IDX < 2)
      {      

        // Simulation
        // .Size=::Component.Property.GetValue(this, .propStr)

        // Decision
        if (FCL_SIZE == 0)
        {        

          // Don't add - we don't need this variable
          FCR_RETVAL = 0;

        // } else {

        }

      } else {

        // Don't add - we don't need this variable
        FCR_RETVAL = 0;

      }

    // } else {

    }

  }

  return (FCR_RETVAL);

  //Local variable definitions
  #undef FCLsz_VARSTR
  #undef FCLsz_PROPSTR
  #undef FCLsz_VARNAME
  #undef FCLsz_EXPANDNAME
}

/*=----------------------------------------------------------------------=*\
   Use :Collects a single value from each of the connected input buffers and places in order into the output buffer.
\*=----------------------------------------------------------------------=*/
void FCM_Interlace()
{
  //Local variable definitions
  MX_UINT8 FCL_VAL;


  // Decision
  if (2 > 0)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref1_Get(FCV_INDEXIN0));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref1_Get(FCV_INDEXIN0));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref1_Get(FCV_INDEXIN0));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN0 = FCV_INDEXIN0 + 1;

      // Decision
      if (FCV_INDEXIN0 == 0)
      {      

        // Calculation
        FCV_INDEXIN0 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 1)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref2_Get(FCV_INDEXIN1));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref2_Get(FCV_INDEXIN1));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref2_Get(FCV_INDEXIN1));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN1 = FCV_INDEXIN1 + 1;

      // Decision
      if (FCV_INDEXIN1 == 0)
      {      

        // Calculation
        FCV_INDEXIN1 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 2)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref3_Get(FCV_INDEXIN2));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref3_Get(FCV_INDEXIN2));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref3_Get(FCV_INDEXIN2));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN2 = FCV_INDEXIN2 + 1;

      // Decision
      if (FCV_INDEXIN2 == 0)
      {      

        // Calculation
        FCV_INDEXIN2 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 3)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref4_Get(FCV_INDEXIN3));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref4_Get(FCV_INDEXIN3));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref4_Get(FCV_INDEXIN3));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN3 = FCV_INDEXIN3 + 1;

      // Decision
      if (FCV_INDEXIN3 == 0)
      {      

        // Calculation
        FCV_INDEXIN3 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 4)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref5_Get(FCV_INDEXIN4));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref5_Get(FCV_INDEXIN4));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref5_Get(FCV_INDEXIN4));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN4 = FCV_INDEXIN4 + 1;

      // Decision
      if (FCV_INDEXIN4 == 0)
      {      

        // Calculation
        FCV_INDEXIN4 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 5)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref6_Get(FCV_INDEXIN5));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref6_Get(FCV_INDEXIN5));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref6_Get(FCV_INDEXIN5));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN5 = FCV_INDEXIN5 + 1;

      // Decision
      if (FCV_INDEXIN5 == 0)
      {      

        // Calculation
        FCV_INDEXIN5 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 6)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref7_Get(FCV_INDEXIN6));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref7_Get(FCV_INDEXIN6));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref7_Get(FCV_INDEXIN6));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN6 = FCV_INDEXIN6 + 1;

      // Decision
      if (FCV_INDEXIN6 == 0)
      {      

        // Calculation
        FCV_INDEXIN6 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 7)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref8_Get(FCV_INDEXIN7));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref8_Get(FCV_INDEXIN7));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref8_Get(FCV_INDEXIN7));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN7 = FCV_INDEXIN7 + 1;

      // Decision
      if (FCV_INDEXIN7 == 0)
      {      

        // Calculation
        FCV_INDEXIN7 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 8)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref9_Get(FCV_INDEXIN8));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref9_Get(FCV_INDEXIN8));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref9_Get(FCV_INDEXIN8));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN8 = FCV_INDEXIN8 + 1;

      // Decision
      if (FCV_INDEXIN8 == 0)
      {      

        // Calculation
        FCV_INDEXIN8 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 9)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref10_Get(FCV_INDEXIN9));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref10_Get(FCV_INDEXIN9));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref10_Get(FCV_INDEXIN9));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN9 = FCV_INDEXIN9 + 1;

      // Decision
      if (FCV_INDEXIN9 == 0)
      {      

        // Calculation
        FCV_INDEXIN9 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 10)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref11_Get(FCV_INDEXIN10));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref11_Get(FCV_INDEXIN10));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref11_Get(FCV_INDEXIN10));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN10 = FCV_INDEXIN10 + 1;

      // Decision
      if (FCV_INDEXIN10 == 0)
      {      

        // Calculation
        FCV_INDEXIN10 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 11)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref12_Get(FCV_INDEXIN11));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref12_Get(FCV_INDEXIN11));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref12_Get(FCV_INDEXIN11));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN11 = FCV_INDEXIN11 + 1;

      // Decision
      if (FCV_INDEXIN11 == 0)
      {      

        // Calculation
        FCV_INDEXIN11 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 12)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref13_Get(FCV_INDEXIN12));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref13_Get(FCV_INDEXIN12));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref13_Get(FCV_INDEXIN12));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN12 = FCV_INDEXIN12 + 1;

      // Decision
      if (FCV_INDEXIN12 == 0)
      {      

        // Calculation
        FCV_INDEXIN12 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 13)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref14_Get(FCV_INDEXIN13));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref14_Get(FCV_INDEXIN13));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref14_Get(FCV_INDEXIN13));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN13 = FCV_INDEXIN13 + 1;

      // Decision
      if (FCV_INDEXIN13 == 0)
      {      

        // Calculation
        FCV_INDEXIN13 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 14)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref15_Get(FCV_INDEXIN14));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref15_Get(FCV_INDEXIN14));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref15_Get(FCV_INDEXIN14));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN14 = FCV_INDEXIN14 + 1;

      // Decision
      if (FCV_INDEXIN14 == 0)
      {      

        // Calculation
        FCV_INDEXIN14 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (2 > 15)
  {  

    // Decision
    if (0 == 0)
    {    

      // Call Component Macro
      DSPBuff_1_Put(FCV_INDEXOUT, DSP_ILace_Ref16_Get(FCV_INDEXIN15));

      // Calculation
      FCV_INDEXOUT = FCV_INDEXOUT + 1;

    } else {

      // Decision
      if (0 < 3)
      {      

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetInt(0, DSP_ILace_Ref16_Get(FCV_INDEXIN15));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 2;

      } else {

        // Component Macro
        FCD_02571_TypeConversionsFree1__SetLong(DSP_ILace_Ref16_Get(FCV_INDEXIN15));

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(0);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(1);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 1, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(2);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 2, FCL_VAL);

        // Component Macro
        FCL_VAL = FCD_02571_TypeConversionsFree1__GetByte(3);

        // Call Component Macro
        DSPBuff_1_Put(FCV_INDEXOUT + 3, FCL_VAL);

        // Calculation
        FCV_INDEXOUT = FCV_INDEXOUT + 4;

      }

    }

    // Decision
    if (0 > 1)
    {    

      // Calculation
      FCV_INDEXIN15 = FCV_INDEXIN15 + 1;

      // Decision
      if (FCV_INDEXIN15 == 0)
      {      

        // Calculation
        FCV_INDEXIN15 = 0;

      // } else {

      }

    // } else {

    }

  // } else {

  }

  // Decision
  if (FCV_INDEXOUT >= 2)
  {  

    // Calculation
    FCV_INDEXOUT = 0;

  // } else {

  }

}

/*=----------------------------------------------------------------------=*\
   Use :Sent to a component to allow dynamic amendment of header code
       :
       :Parameters for macro Ev_AddHeader:
       :  HeadCode[20] : Text to amend for header
       :
       :Returns : Non-zero to block header code insertion
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_AddHeader(MX_CHAR *FCL_HEADCODE, MX_UINT16 FCLsz_HEADCODE)
{
  //Local variable definitions
  #define FCLsz_CMPNAME 20
  MX_CHAR FCL_CMPNAME[FCLsz_CMPNAME];
  MX_UINT8 FCL_IDX;
  #define FCLsz_STR1 20
  MX_CHAR FCL_STR1[FCLsz_STR1];
  #define FCLsz_STR2 20
  MX_CHAR FCL_STR2[FCLsz_STR2];
  #define FCLsz_PROPNAME 20
  MX_CHAR FCL_PROPNAME[FCLsz_PROPNAME];
  MX_UINT32 FCR_RETVAL; // Non-zero to block header code insertion


  // Calculation
  FCR_RETVAL = 1;

  // Simulation
  // .CmpName=::Tree.GetName(this)

  return (FCR_RETVAL);

  //Local variable definitions
  #undef FCLsz_CMPNAME
  #undef FCLsz_STR1
  #undef FCLsz_STR2
  #undef FCLsz_PROPNAME
}

/*=----------------------------------------------------------------------=*\
   Use :Sent to the mouse target when the user has altered the position of a component child
       :
       :Parameters for macro Ev_Resize:
       :  Component : The component that has been altered
       :  PrevPos : The position of the object before the start of positioning
       :  Final : True if this is the end of a drag operation
       :
       :Returns : MX_UINT32
\*=----------------------------------------------------------------------=*/
MX_UINT32 FCM_Ev_Resize(MX_UINT32 FCL_COMPONENT, MX_UINT32 FCL_PREVPOS, MX_BOOL FCL_FINAL)
{
  //Local variable definitions
  MX_UINT8 FCL_IDX;
  #define FCLsz_NAME 20
  MX_CHAR FCL_NAME[FCLsz_NAME];
  MX_UINT32 FCL_HANDLE;
  MX_UINT32 FCR_RETVAL;


  // Loop
  for (FCL_IDX=0; (FCL_IDX)<(2); (FCL_IDX)++)
  {
    // Calculation
    {
    MX_CHAR FCI_TMP_STR[MX_MAX_TMPSTR_SIZE];
    FCI_SHEAD("Ref",4, FCI_TOSTRING(FCL_IDX + 1, FCI_TMP_STR,MX_MAX_TMPSTR_SIZE),20, FCL_NAME,20);
    }

    // Built-in Function
    // .Handle=::Component.FindChild(this, .Name)

    // Built-in Function
    // ::System.Forward(this)

  }

  // Built-in Function
  // ::System.Forward(Buff1)

  return (FCR_RETVAL);

  //Local variable definitions
  #undef FCLsz_NAME
}

/*=----------------------------------------------------------------------=*\
   Use :Repeats the interlace function as many times as set in the data count property.
\*=----------------------------------------------------------------------=*/
void FCM_InterlaceArray()
{
  //Local variable definitions
  MX_UINT8 FCL_IDX;


  // Loop
  for (FCL_IDX=0; (FCL_IDX)<(1); (FCL_IDX)++)
  {
    // User Macro
    FCM_Interlace();

  }

}



/*========================================================================*\
   Use :Main
\*========================================================================*/
void main()
{
	#ifdef INTOSCHELPER
		INTOSCHELPERCODE
	#endif
ADCON1 = 0x07;

OPTION_REG = 0xC0;


	mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Interrupt
\*========================================================================*/
void MX_INTERRUPT_MACRO(void)
{

}




