//************************************************************************************
//**  
//**  Source name:   C:\Users\medel\OneDrive - MATRIX TECHNOLOGY SOLUTIONS\FC10\Components\IO_Source\DSP\DSP_Interlace.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.16F.16F877A
//**  
//**  Generated by:  Flowcode v11.0.0.8
//**  Date:          Thursday, October 30, 2025 15:41:09
//**  Users:         1
//**  Registered to: medelec35 (65920724)
//**  Licence key: 5Q78FW
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_PIC

#define MX_CAL_PIC

#define MX_CLK_SPEED 19660800

#define FCP_NULL Unconnected_Port


#include <xc.h>
#include <math.h>
//Chip Configuration Settings
__PROG_CONFIG(0x1, 0x3F72);

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"




MX_UINT32 FCM_Ev_Timer(MX_UINT32 FCL_TIMERID);
MX_UINT32 FCM_Ev_Property();
MX_UINT32 FCM_Ev_LoadComplete();
MX_UINT8 FCM_Prv_GetTypeBytes(MX_CHAR *FCL_TYPESTR, MX_UINT16 FCLsz_TYPESTR);
MX_UINT32 FCM_Ev_AddVar(MX_CHAR *PFCL_VARNAME, MX_CHAR *PFCL_EXPANDNAME, MX_CHAR *FCL_EXPANSION, MX_UINT16 FCLsz_EXPANSION);
void FCM_Interlace();
MX_UINT32 FCM_Ev_AddHeader(MX_CHAR *FCL_HEADCODE, MX_UINT16 FCLsz_HEADCODE);
MX_UINT32 FCM_Ev_Resize(MX_UINT32 FCL_COMPONENT, MX_UINT32 FCL_PREVPOS, MX_BOOL FCL_FINAL);
void FCM_InterlaceArray();

/*========================================================================*\
   Use :Ref16
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref16
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref16_Put DSPBuff_0_Put
#define DSP_ILace_Ref16_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref15
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref15
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref15_Put DSPBuff_0_Put
#define DSP_ILace_Ref15_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref14
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref14
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref14_Put DSPBuff_0_Put
#define DSP_ILace_Ref14_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref13
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref13
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref13_Put DSPBuff_0_Put
#define DSP_ILace_Ref13_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref12
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref12
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref12_Put DSPBuff_0_Put
#define DSP_ILace_Ref12_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref11
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref11
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref11_Put DSPBuff_0_Put
#define DSP_ILace_Ref11_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref10
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref10
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref10_Put DSPBuff_0_Put
#define DSP_ILace_Ref10_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref9
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref9
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref9_Put DSPBuff_0_Put
#define DSP_ILace_Ref9_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref8
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref8
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref8_Put DSPBuff_0_Put
#define DSP_ILace_Ref8_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref7
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref7
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref7_Put DSPBuff_0_Put
#define DSP_ILace_Ref7_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref6
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref6
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref6_Put DSPBuff_0_Put
#define DSP_ILace_Ref6_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref5
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref5
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref5_Put DSPBuff_0_Put
#define DSP_ILace_Ref5_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref4
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref4
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref4_Put DSPBuff_0_Put
#define DSP_ILace_Ref4_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref3
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref3
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref3_Put DSPBuff_0_Put
#define DSP_ILace_Ref3_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref2
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref2
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref2_Put DSPBuff_0_Put
#define DSP_ILace_Ref2_Get DSPBuff_0_Get

/*========================================================================*\
   Use :Ref1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Ref1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define DSP_ILace_Ref1_Put DSPBuff_0_Put
#define DSP_ILace_Ref1_Get DSPBuff_0_Get

/*========================================================================*\
   Use :TypeConversionsFree1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02571_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02571_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02571_TypeConversionsFree1__GetFloat();
MX_UINT32 FCD_02571_TypeConversionsFree1__GetLong();
MX_UINT16 FCD_02571_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02571_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :Buff1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :Buff1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
//DSP Output Buffer for DSP_ILace
unsigned char DSPBuff_1[2];
#define DSPBuff_1_Put(Idx,Val) DSPBuff_1[Idx] = (unsigned char ) Val
#define DSPBuff_1_Get(Idx) (unsigned char ) DSPBuff_1[Idx]


/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"

